# Generated by Django 6.1 on 2026-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_checked_in_at_ticket_checked_in_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='benefits',
            field=models.TextField(blank=True, help_text='One benefit per line, e.g.\nAccess to main floor\nCash bar\nFree T-shirt'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='description',
            field=models.CharField(blank=True, help_text="One-line description, e.g. 'Standard entry with cash bar access'.", max_length=300),
        ),
    ]
