[phases.build]
cmds = ["cd ticketing_platform && python manage.py collectstatic --noinput"]

[start]
cmd = "cd ticketing_platform && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
