# Generated by Django 6.1 on 2026-09-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('conference', 'Conference'), ('meetup', 'Meetup'), ('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('concert', 'Concert'), ('sports', 'Sports'), ('networking', 'Networking'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_color',
            field=models.CharField(blank=True, default='', help_text='Banner accent colour as hex, e.g. #5B4CF5', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.URLField(blank=True, help_text='URL of a banner/cover image for the event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Optional end date/time.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_type',
            field=models.CharField(blank=True, choices=[('in_person', 'In Person'), ('online', 'Online'), ('hybrid', 'Hybrid')], default='in_person', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. AI, Python, Beginner', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, help_text='External event website or registration link.'),
        ),
    ]
